site_name: Lanbao's Blog
repo_url: https://github.com/lanbaoshen/lanbaoshen.github.io
repo_name: lanbaoshen.github.io

theme:
  name: material
  palette:
    scheme: slate
    primary: black
  language: en
  features:
    - content.code.copy
    - content.tabs.link
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - toc.follow
  icon:
    repo: fontawesome/brands/github-alt
  custom_dir: overrides

plugins:
  - meta
  - search
  - termynal:
      prompt_literal_start:
        - "$"
        - ">>>"
  - blog:
      enabled: true
      blog_toc: true
      post_excerpt: required
      archive_date_format: yyyy
  - redirects:
      redirect_maps:
        index.md: blog/index.md

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/lanbaoshen

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
